# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XYyvjhcjozdzDu5HTVl849byDSN9Cm2H
"""

from flask import Flask, render_template, request, jsonify
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array
import cv2
import numpy as np
from PIL import Image
import os

app = Flask(__name__)
model = load_model("/content/happy_not_happy_cnn.h5")

def preprocess(img):
    if img.mode != "RGB":
        img = img.convert("RGB")
    img = img.resize((48, 48))
    img_array = img_to_array(img)
    img_array = img_array / 255.0
    return np.expand_dims(img_array, axis=0)

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():
    if "file" not in request.files:
        return jsonify({"error": "No file uploaded"}), 400

    file = request.files["file"]
    img = Image.open(file.stream)
    processed = preprocess(img)
    prediction = model.predict(processed)[0][0]
    label = "Happy 😊" if prediction > 0.5 else "Not Happy 😐"
    return jsonify({"result": label})

if __name__ == "__main__":
    app.run(debug=True)